### ISSUE TITLE
Event/Migrations not works with the new modeltranslation implementation in mezzanine.

### ISSUE THREAD

**Issue by itztli** [stbarnabas/mezzanine-events#27]
Few months ago, mezzanine team is testing a new capability of multi-language sites adding modeltranslation in the project. 

I create a new project using the last version of mezzanine from git and restore a previous database project that includes mezzanine-events pages. Then, I create a new class to register the translation. When I run the server all is ok but when I run migrations I found the following error:

 python manage.py migrate
/home/vdelaluz/virtualenvs/veso/local/lib/python2.7/site-packages/Mezzanine-3.1.10-py2.7.egg/mezzanine/generic/fields.py:6: RemovedInDjango19Warning: django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and admin submodules of django.contrib.contenttypes.
  from django.contrib.contenttypes.generic import GenericRelation

Operations to perform:
  Synchronize unmigrated apps: staticfiles, boot, modeltranslation, filebrowser_safe, sitemaps, dbbackup, mezzanine_events, grappelli_safe
  Apply all migrations: core, redirects, django_comments, sessions, admin, twitter, galleries, sites, auth, blog, generic, contenttypes, conf, forms, pages
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states...Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vdelaluz/virtualenvs/veso/local/lib/python2.7/site-packages/Django-1.8.2-py2.7.egg/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/vdelaluz/virtualenvs/veso/local/lib/python2.7/site-packages/Django-1.8.2-py2.7.egg/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vdelaluz/virtualenvs/veso/local/lib/python2.7/site-packages/Django-1.8.2-py2.7.egg/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/vdelaluz/virtualenvs/veso/local/lib/python2.7/site-packages/Django-1.8.2-py2.7.egg/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/home/vdelaluz/virtualenvs/veso/local/lib/python2.7/site-packages/Django-1.8.2-py2.7.egg/django/core/management/commands/migrate.py", line 221, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/home/vdelaluz/virtualenvs/veso/local/lib/python2.7/site-packages/Django-1.8.2-py2.7.egg/django/db/migrations/executor.py", line 100, in migrate
    state.apps  # Render all real_apps -- performance critical
  File "/home/vdelaluz/virtualenvs/veso/local/lib/python2.7/site-packages/Django-1.8.2-py2.7.egg/django/utils/functional.py", line 60, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/vdelaluz/virtualenvs/veso/local/lib/python2.7/site-packages/Django-1.8.2-py2.7.egg/django/db/migrations/state.py", line 166, in apps
    return StateApps(self.real_apps, self.models)
  File "/home/vdelaluz/virtualenvs/veso/local/lib/python2.7/site-packages/Django-1.8.2-py2.7.egg/django/db/migrations/state.py", line 232, in __init__
    self.render_multiple(list(models.values()) + self.real_models)
  File "/home/vdelaluz/virtualenvs/veso/local/lib/python2.7/site-packages/Django-1.8.2-py2.7.egg/django/db/migrations/state.py", line 270, in render_multiple
    "for more" % (new_unrendered_models, get_docs_version())
django.db.migrations.state.InvalidBasesError: Cannot resolve bases for [<ModelState: 'mezzanine_events.Event'>, <ModelState: 'mezzanine_events.EventContainer'>]
This can happen if you are inheriting models from an app with migrations (e.g. contrib.auth)
 in an app with no migrations; see https://docs.djangoproject.com/en/1.8/topics/migrations/#dependencies for more

**Comment by itztli** [comment]
I made another test with new project and new database and also fails:

`python manage.py createdb
/home/vdelaluz/virtualenvs/sciesmex2015/local/lib/python2.7/site-packages/Mezzanine-3.1.10-py2.7.egg/mezzanine/utils/conf.py:51: UserWarning: You haven't defined the ALLOWED_HOSTS settings, which Django requires. Will fall back to the domains configured as sites.
  warn("You haven't defined the ALLOWED_HOSTS settings, which "
/home/vdelaluz/virtualenvs/sciesmex2015/local/lib/python2.7/site-packages/Mezzanine-3.1.10-py2.7.egg/mezzanine/generic/fields.py:6: RemovedInDjango19Warning: django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and admin submodules of django.contrib.contenttypes.
  from django.contrib.contenttypes.generic import GenericRelation

Operations to perform:
  Synchronize unmigrated apps: staticfiles, boot, modeltranslation, filebrowser_safe, sitemaps, dbbackup, mezzanine_events, grappelli_safe
  Apply all migrations: core, redirects, django_comments, sessions, admin, twitter, galleries, sites, auth, blog, generic, contenttypes, conf, forms, pages
Synchronizing apps without migrations:
  Creating tables...
    Creating table mezzanine_events_event
    Creating table mezzanine_events_eventcontainer
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states...Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vdelaluz/virtualenvs/sciesmex2015/local/lib/python2.7/site-packages/Django-1.8.2-py2.7.egg/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/vdelaluz/virtualenvs/sciesmex2015/local/lib/python2.7/site-packages/Django-1.8.2-py2.7.egg/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vdelaluz/virtualenvs/sciesmex2015/local/lib/python2.7/site-packages/Django-1.8.2-py2.7.egg/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/vdelaluz/virtualenvs/sciesmex2015/local/lib/python2.7/site-packages/Django-1.8.2-py2.7.egg/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/home/vdelaluz/virtualenvs/sciesmex2015/local/lib/python2.7/site-packages/Mezzanine-3.1.10-py2.7.egg/mezzanine/core/management/commands/createdb.py", line 60, in handle
    interactive=self.interactive)
  File "/home/vdelaluz/virtualenvs/sciesmex2015/local/lib/python2.7/site-packages/Django-1.8.2-py2.7.egg/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/home/vdelaluz/virtualenvs/sciesmex2015/local/lib/python2.7/site-packages/Django-1.8.2-py2.7.egg/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/home/vdelaluz/virtualenvs/sciesmex2015/local/lib/python2.7/site-packages/Django-1.8.2-py2.7.egg/django/core/management/commands/migrate.py", line 221, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/home/vdelaluz/virtualenvs/sciesmex2015/local/lib/python2.7/site-packages/Django-1.8.2-py2.7.egg/django/db/migrations/executor.py", line 100, in migrate
    state.apps  # Render all real_apps -- performance critical
  File "/home/vdelaluz/virtualenvs/sciesmex2015/local/lib/python2.7/site-packages/Django-1.8.2-py2.7.egg/django/utils/functional.py", line 60, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/vdelaluz/virtualenvs/sciesmex2015/local/lib/python2.7/site-packages/Django-1.8.2-py2.7.egg/django/db/migrations/state.py", line 166, in apps
    return StateApps(self.real_apps, self.models)
  File "/home/vdelaluz/virtualenvs/sciesmex2015/local/lib/python2.7/site-packages/Django-1.8.2-py2.7.egg/django/db/migrations/state.py", line 232, in __init__
    self.render_multiple(list(models.values()) + self.real_models)
  File "/home/vdelaluz/virtualenvs/sciesmex2015/local/lib/python2.7/site-packages/Django-1.8.2-py2.7.egg/django/db/migrations/state.py", line 270, in render_multiple
    "for more" % (new_unrendered_models, get_docs_version())
django.db.migrations.state.InvalidBasesError: Cannot resolve bases for [<ModelState: 'mezzanine_events.Event'>, <ModelState: 'mezzanine_events.EventContainer'>]
This can happen if you are inheriting models from an app with migrations (e.g. contrib.auth)
 in an app with no migrations; see https://docs.djangoproject.com/en/1.8/topics/migrations/#dependencies for morepython manage.py createdb
/home/vdelaluz/virtualenvs/sciesmex2015/local/lib/python2.7/site-packages/Mezzanine-3.1.10-py2.7.egg/mezzanine/utils/conf.py:51: UserWarning: You haven't defined the ALLOWED_HOSTS settings, which Django requires. Will fall back to the domains configured as sites.
  warn("You haven't defined the ALLOWED_HOSTS settings, which "
/home/vdelaluz/virtualenvs/sciesmex2015/local/lib/python2.7/site-packages/Mezzanine-3.1.10-py2.7.egg/mezzanine/generic/fields.py:6: RemovedInDjango19Warning: django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and admin submodules of django.contrib.contenttypes.
  from django.contrib.contenttypes.generic import GenericRelation

Operations to perform:
  Synchronize unmigrated apps: staticfiles, boot, modeltranslation, filebrowser_safe, sitemaps, dbbackup, mezzanine_events, grappelli_safe
  Apply all migrations: core, redirects, django_comments, sessions, admin, twitter, galleries, sites, auth, blog, generic, contenttypes, conf, forms, pages
Synchronizing apps without migrations:
  Creating tables...
    Creating table mezzanine_events_event
    Creating table mezzanine_events_eventcontainer
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states...Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vdelaluz/virtualenvs/sciesmex2015/local/lib/python2.7/site-packages/Django-1.8.2-py2.7.egg/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/vdelaluz/virtualenvs/sciesmex2015/local/lib/python2.7/site-packages/Django-1.8.2-py2.7.egg/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vdelaluz/virtualenvs/sciesmex2015/local/lib/python2.7/site-packages/Django-1.8.2-py2.7.egg/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/vdelaluz/virtualenvs/sciesmex2015/local/lib/python2.7/site-packages/Django-1.8.2-py2.7.egg/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/home/vdelaluz/virtualenvs/sciesmex2015/local/lib/python2.7/site-packages/Mezzanine-3.1.10-py2.7.egg/mezzanine/core/management/commands/createdb.py", line 60, in handle
    interactive=self.interactive)
  File "/home/vdelaluz/virtualenvs/sciesmex2015/local/lib/python2.7/site-packages/Django-1.8.2-py2.7.egg/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/home/vdelaluz/virtualenvs/sciesmex2015/local/lib/python2.7/site-packages/Django-1.8.2-py2.7.egg/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/home/vdelaluz/virtualenvs/sciesmex2015/local/lib/python2.7/site-packages/Django-1.8.2-py2.7.egg/django/core/management/commands/migrate.py", line 221, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/home/vdelaluz/virtualenvs/sciesmex2015/local/lib/python2.7/site-packages/Django-1.8.2-py2.7.egg/django/db/migrations/executor.py", line 100, in migrate
    state.apps  # Render all real_apps -- performance critical
  File "/home/vdelaluz/virtualenvs/sciesmex2015/local/lib/python2.7/site-packages/Django-1.8.2-py2.7.egg/django/utils/functional.py", line 60, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/vdelaluz/virtualenvs/sciesmex2015/local/lib/python2.7/site-packages/Django-1.8.2-py2.7.egg/django/db/migrations/state.py", line 166, in apps
    return StateApps(self.real_apps, self.models)
  File "/home/vdelaluz/virtualenvs/sciesmex2015/local/lib/python2.7/site-packages/Django-1.8.2-py2.7.egg/django/db/migrations/state.py", line 232, in __init__
    self.render_multiple(list(models.values()) + self.real_models)
  File "/home/vdelaluz/virtualenvs/sciesmex2015/local/lib/python2.7/site-packages/Django-1.8.2-py2.7.egg/django/db/migrations/state.py", line 270, in render_multiple
    "for more" % (new_unrendered_models, get_docs_version())
django.db.migrations.state.InvalidBasesError: Cannot resolve bases for [<ModelState: 'mezzanine_events.Event'>, <ModelState: 'mezzanine_events.EventContainer'>]
This can happen if you are inheriting models from an app with migrations (e.g. contrib.auth)
 in an app with no migrations; see https://docs.djangoproject.com/en/1.8/topics/migrations/#dependencies for more`
